### PR TITLE
S3 Sink

### PR DESCRIPTION
**Pull request by alok87**
## S3 Sink

S3 sink to store events data in s3. 

Two data storage format are supported at present
- **Flat JSON format:** This format will be useful if we want to load data in Redshift for analysis and visualisation. It can be easily integrated with Redshift with a simple Lamda function. (Default)
- **RFC5424 (syslog) format:** same as HTTP Sink 

The s3 to redshift integration details would be documented as a separate PR. It is a small Lamda code.

Solves: https://github.com/heptiolabs/eventrouter/issues/63

```bash
$ ./eventrouter -v 3 -logtostderr
I0905 15:40:32.964536   56860 interfaces.go:37] Sink is [s3sink]
I0905 15:40:32.965943   56860 main.go:131] Starting shared Informer(s)
I0905 15:40:32.965994   56860 main.go:118] Starting prometheus metrics.
I0905 15:40:32.966872   56860 eventrouter.go:100] Starting EventRouter
I0905 15:40:32.968483   56860 reflector.go:202] Starting reflector *v1.Event (30m0s) from github.com/heptiolabs/eventrouter/vendor/k8s.io/client-go/informers/factory.go:73
I0905 15:40:32.968544   56860 reflector.go:240] Listing and watching *v1.Event from github.com/heptiolabs/eventrouter/vendor/k8s.io/client-go/informers/factory.go:73
I0905 15:40:35.588933   56860 s3sink.go:198] Uploaded at s3bucket/cluster-1/events/2018/9/5/1536142235195234000.txt
I0905 15:41:40.922273   56860 s3sink.go:198] Uploaded at s3bucket/cluster-1/events/2018/9/5/1536142300252857000.txt
I0905 15:42:43.984785   56860 s3sink.go:198] Uploaded at s3bucket/cluster-1/events/2018/9/5/1536142363705213000.txt
```

### CODE REVIEW

**Comment by timothysc** [comment]
@alok87 - could you flatten to 2 commits please 
1 - code adds 
2 - vendor'd code.

**Comment by alok87** [comment]
@timothysc Done
Vendor code is huge but because of aws sdk

**Comment by alok87** [comment]
@timothysc can you please take a look. All is done from my side. Want to use it from the released branch.

**Comment by alok87** [comment]
@timothysc ping

**Pull request merged**
