### PR TITLE
Add support for event type Info and Unknown

### PR DESCRIPTION
**Pull request by richm**
Add support for prometheus counters for types
Info and Unknown

### CODE REVIEW

**Comment by johnSchnake** [comment]
@richm Looks good as far as I can tell; do you have a way to reproduce this that I can run through?

Also, be sure to sign your commit.

**Comment by richm** [comment]
> @richm Looks good as far as I can tell; do you have a way to reproduce this that I can run through?

The test starts here: https://github.com/openshift/origin-aggregated-logging/blob/master/test/eventrouter.sh#L129

Basically, create an event with `"type": "Info"`, and see if the eventrouter will process it correctly (in our case, that also means passing through Fluentd and Elasticsearch, but obviously you won't need to do that for just eventrouter verification).  You might also want to create an event with some other type, to see if it is correctly processed and counted by Prometheus as an "unknown" type.

> Also, be sure to sign your commit.

Done.

**Comment by iamsudip** [comment]
Looking forward to this PR getting released soon. Thanks @richm

**Comment by johnSchnake** [comment]
I pushed one of the other fixes; can you rebase accordingly? The registration lines go in the NewEventRouter method now to ensure their values are ready for use.

**Comment by richm** [comment]
> I pushed one of the other fixes; can you rebase accordingly? The registration lines go in the NewEventRouter method now to ensure their values are ready for use.

Done

**Pull request merged**
